# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yuyangh/test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yuyangh/test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuyangh/test/CMakeFiles /home/yuyangh/test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuyangh/test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named epoll_server

# Build rule for target.
epoll_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 epoll_server
.PHONY : epoll_server

# fast build rule for target.
epoll_server/fast:
	$(MAKE) -f CMakeFiles/epoll_server.dir/build.make CMakeFiles/epoll_server.dir/build
.PHONY : epoll_server/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named client_pool

# Build rule for target.
client_pool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_pool
.PHONY : client_pool

# fast build rule for target.
client_pool/fast:
	$(MAKE) -f CMakeFiles/client_pool.dir/build.make CMakeFiles/client_pool.dir/build
.PHONY : client_pool/fast

#=============================================================================
# Target rules for targets named epoll_server_example

# Build rule for target.
epoll_server_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 epoll_server_example
.PHONY : epoll_server_example

# fast build rule for target.
epoll_server_example/fast:
	$(MAKE) -f CMakeFiles/epoll_server_example.dir/build.make CMakeFiles/epoll_server_example.dir/build
.PHONY : epoll_server_example/fast

client.o: client.cpp.o

.PHONY : client.o

# target to build an object file
client.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cpp.o
.PHONY : client.cpp.o

client.i: client.cpp.i

.PHONY : client.i

# target to preprocess a source file
client.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cpp.i
.PHONY : client.cpp.i

client.s: client.cpp.s

.PHONY : client.s

# target to generate assembly for a file
client.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cpp.s
.PHONY : client.cpp.s

client_pool.o: client_pool.cpp.o

.PHONY : client_pool.o

# target to build an object file
client_pool.cpp.o:
	$(MAKE) -f CMakeFiles/client_pool.dir/build.make CMakeFiles/client_pool.dir/client_pool.cpp.o
.PHONY : client_pool.cpp.o

client_pool.i: client_pool.cpp.i

.PHONY : client_pool.i

# target to preprocess a source file
client_pool.cpp.i:
	$(MAKE) -f CMakeFiles/client_pool.dir/build.make CMakeFiles/client_pool.dir/client_pool.cpp.i
.PHONY : client_pool.cpp.i

client_pool.s: client_pool.cpp.s

.PHONY : client_pool.s

# target to generate assembly for a file
client_pool.cpp.s:
	$(MAKE) -f CMakeFiles/client_pool.dir/build.make CMakeFiles/client_pool.dir/client_pool.cpp.s
.PHONY : client_pool.cpp.s

epoll_server.o: epoll_server.cpp.o

.PHONY : epoll_server.o

# target to build an object file
epoll_server.cpp.o:
	$(MAKE) -f CMakeFiles/epoll_server.dir/build.make CMakeFiles/epoll_server.dir/epoll_server.cpp.o
.PHONY : epoll_server.cpp.o

epoll_server.i: epoll_server.cpp.i

.PHONY : epoll_server.i

# target to preprocess a source file
epoll_server.cpp.i:
	$(MAKE) -f CMakeFiles/epoll_server.dir/build.make CMakeFiles/epoll_server.dir/epoll_server.cpp.i
.PHONY : epoll_server.cpp.i

epoll_server.s: epoll_server.cpp.s

.PHONY : epoll_server.s

# target to generate assembly for a file
epoll_server.cpp.s:
	$(MAKE) -f CMakeFiles/epoll_server.dir/build.make CMakeFiles/epoll_server.dir/epoll_server.cpp.s
.PHONY : epoll_server.cpp.s

epoll_server_example.o: epoll_server_example.cpp.o

.PHONY : epoll_server_example.o

# target to build an object file
epoll_server_example.cpp.o:
	$(MAKE) -f CMakeFiles/epoll_server_example.dir/build.make CMakeFiles/epoll_server_example.dir/epoll_server_example.cpp.o
.PHONY : epoll_server_example.cpp.o

epoll_server_example.i: epoll_server_example.cpp.i

.PHONY : epoll_server_example.i

# target to preprocess a source file
epoll_server_example.cpp.i:
	$(MAKE) -f CMakeFiles/epoll_server_example.dir/build.make CMakeFiles/epoll_server_example.dir/epoll_server_example.cpp.i
.PHONY : epoll_server_example.cpp.i

epoll_server_example.s: epoll_server_example.cpp.s

.PHONY : epoll_server_example.s

# target to generate assembly for a file
epoll_server_example.cpp.s:
	$(MAKE) -f CMakeFiles/epoll_server_example.dir/build.make CMakeFiles/epoll_server_example.dir/epoll_server_example.cpp.s
.PHONY : epoll_server_example.cpp.s

server.o: server.cpp.o

.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i

.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s

.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cpp.s
.PHONY : server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... epoll_server"
	@echo "... edit_cache"
	@echo "... server"
	@echo "... client"
	@echo "... client_pool"
	@echo "... epoll_server_example"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... client_pool.o"
	@echo "... client_pool.i"
	@echo "... client_pool.s"
	@echo "... epoll_server.o"
	@echo "... epoll_server.i"
	@echo "... epoll_server.s"
	@echo "... epoll_server_example.o"
	@echo "... epoll_server_example.i"
	@echo "... epoll_server_example.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

