# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yuyangh/test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yuyangh/test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuyangh/test/CMakeFiles /home/yuyangh/test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuyangh/test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named epoll_server_example

# Build rule for target.
epoll_server_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 epoll_server_example
.PHONY : epoll_server_example

# fast build rule for target.
epoll_server_example/fast:
	$(MAKE) -f CMakeFiles/epoll_server_example.dir/build.make CMakeFiles/epoll_server_example.dir/build
.PHONY : epoll_server_example/fast

#=============================================================================
# Target rules for targets named single_client

# Build rule for target.
single_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 single_client
.PHONY : single_client

# fast build rule for target.
single_client/fast:
	$(MAKE) -f CMakeFiles/single_client.dir/build.make CMakeFiles/single_client.dir/build
.PHONY : single_client/fast

#=============================================================================
# Target rules for targets named single_queue_epoll_server

# Build rule for target.
single_queue_epoll_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 single_queue_epoll_server
.PHONY : single_queue_epoll_server

# fast build rule for target.
single_queue_epoll_server/fast:
	$(MAKE) -f CMakeFiles/single_queue_epoll_server.dir/build.make CMakeFiles/single_queue_epoll_server.dir/build
.PHONY : single_queue_epoll_server/fast

#=============================================================================
# Target rules for targets named single_thread_libevent_server

# Build rule for target.
single_thread_libevent_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 single_thread_libevent_server
.PHONY : single_thread_libevent_server

# fast build rule for target.
single_thread_libevent_server/fast:
	$(MAKE) -f CMakeFiles/single_thread_libevent_server.dir/build.make CMakeFiles/single_thread_libevent_server.dir/build
.PHONY : single_thread_libevent_server/fast

#=============================================================================
# Target rules for targets named multi_thread_libevent_server

# Build rule for target.
multi_thread_libevent_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multi_thread_libevent_server
.PHONY : multi_thread_libevent_server

# fast build rule for target.
multi_thread_libevent_server/fast:
	$(MAKE) -f CMakeFiles/multi_thread_libevent_server.dir/build.make CMakeFiles/multi_thread_libevent_server.dir/build
.PHONY : multi_thread_libevent_server/fast

#=============================================================================
# Target rules for targets named basic_server

# Build rule for target.
basic_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic_server
.PHONY : basic_server

# fast build rule for target.
basic_server/fast:
	$(MAKE) -f CMakeFiles/basic_server.dir/build.make CMakeFiles/basic_server.dir/build
.PHONY : basic_server/fast

#=============================================================================
# Target rules for targets named libevent_server_ref

# Build rule for target.
libevent_server_ref: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libevent_server_ref
.PHONY : libevent_server_ref

# fast build rule for target.
libevent_server_ref/fast:
	$(MAKE) -f CMakeFiles/libevent_server_ref.dir/build.make CMakeFiles/libevent_server_ref.dir/build
.PHONY : libevent_server_ref/fast

#=============================================================================
# Target rules for targets named client_pool

# Build rule for target.
client_pool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_pool
.PHONY : client_pool

# fast build rule for target.
client_pool/fast:
	$(MAKE) -f CMakeFiles/client_pool.dir/build.make CMakeFiles/client_pool.dir/build
.PHONY : client_pool/fast

#=============================================================================
# Target rules for targets named multi_queue_epoll_server

# Build rule for target.
multi_queue_epoll_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multi_queue_epoll_server
.PHONY : multi_queue_epoll_server

# fast build rule for target.
multi_queue_epoll_server/fast:
	$(MAKE) -f CMakeFiles/multi_queue_epoll_server.dir/build.make CMakeFiles/multi_queue_epoll_server.dir/build
.PHONY : multi_queue_epoll_server/fast

#=============================================================================
# Target rules for targets named libevent_multi_worker

# Build rule for target.
libevent_multi_worker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libevent_multi_worker
.PHONY : libevent_multi_worker

# fast build rule for target.
libevent_multi_worker/fast:
	$(MAKE) -f CMakeFiles/libevent_multi_worker.dir/build.make CMakeFiles/libevent_multi_worker.dir/build
.PHONY : libevent_multi_worker/fast

basic_server.o: basic_server.cpp.o

.PHONY : basic_server.o

# target to build an object file
basic_server.cpp.o:
	$(MAKE) -f CMakeFiles/basic_server.dir/build.make CMakeFiles/basic_server.dir/basic_server.cpp.o
.PHONY : basic_server.cpp.o

basic_server.i: basic_server.cpp.i

.PHONY : basic_server.i

# target to preprocess a source file
basic_server.cpp.i:
	$(MAKE) -f CMakeFiles/basic_server.dir/build.make CMakeFiles/basic_server.dir/basic_server.cpp.i
.PHONY : basic_server.cpp.i

basic_server.s: basic_server.cpp.s

.PHONY : basic_server.s

# target to generate assembly for a file
basic_server.cpp.s:
	$(MAKE) -f CMakeFiles/basic_server.dir/build.make CMakeFiles/basic_server.dir/basic_server.cpp.s
.PHONY : basic_server.cpp.s

client_pool.o: client_pool.cpp.o

.PHONY : client_pool.o

# target to build an object file
client_pool.cpp.o:
	$(MAKE) -f CMakeFiles/client_pool.dir/build.make CMakeFiles/client_pool.dir/client_pool.cpp.o
.PHONY : client_pool.cpp.o

client_pool.i: client_pool.cpp.i

.PHONY : client_pool.i

# target to preprocess a source file
client_pool.cpp.i:
	$(MAKE) -f CMakeFiles/client_pool.dir/build.make CMakeFiles/client_pool.dir/client_pool.cpp.i
.PHONY : client_pool.cpp.i

client_pool.s: client_pool.cpp.s

.PHONY : client_pool.s

# target to generate assembly for a file
client_pool.cpp.s:
	$(MAKE) -f CMakeFiles/client_pool.dir/build.make CMakeFiles/client_pool.dir/client_pool.cpp.s
.PHONY : client_pool.cpp.s

epoll_server_example.o: epoll_server_example.cpp.o

.PHONY : epoll_server_example.o

# target to build an object file
epoll_server_example.cpp.o:
	$(MAKE) -f CMakeFiles/epoll_server_example.dir/build.make CMakeFiles/epoll_server_example.dir/epoll_server_example.cpp.o
.PHONY : epoll_server_example.cpp.o

epoll_server_example.i: epoll_server_example.cpp.i

.PHONY : epoll_server_example.i

# target to preprocess a source file
epoll_server_example.cpp.i:
	$(MAKE) -f CMakeFiles/epoll_server_example.dir/build.make CMakeFiles/epoll_server_example.dir/epoll_server_example.cpp.i
.PHONY : epoll_server_example.cpp.i

epoll_server_example.s: epoll_server_example.cpp.s

.PHONY : epoll_server_example.s

# target to generate assembly for a file
epoll_server_example.cpp.s:
	$(MAKE) -f CMakeFiles/epoll_server_example.dir/build.make CMakeFiles/epoll_server_example.dir/epoll_server_example.cpp.s
.PHONY : epoll_server_example.cpp.s

libevent_multi_worker.o: libevent_multi_worker.cpp.o

.PHONY : libevent_multi_worker.o

# target to build an object file
libevent_multi_worker.cpp.o:
	$(MAKE) -f CMakeFiles/libevent_multi_worker.dir/build.make CMakeFiles/libevent_multi_worker.dir/libevent_multi_worker.cpp.o
.PHONY : libevent_multi_worker.cpp.o

libevent_multi_worker.i: libevent_multi_worker.cpp.i

.PHONY : libevent_multi_worker.i

# target to preprocess a source file
libevent_multi_worker.cpp.i:
	$(MAKE) -f CMakeFiles/libevent_multi_worker.dir/build.make CMakeFiles/libevent_multi_worker.dir/libevent_multi_worker.cpp.i
.PHONY : libevent_multi_worker.cpp.i

libevent_multi_worker.s: libevent_multi_worker.cpp.s

.PHONY : libevent_multi_worker.s

# target to generate assembly for a file
libevent_multi_worker.cpp.s:
	$(MAKE) -f CMakeFiles/libevent_multi_worker.dir/build.make CMakeFiles/libevent_multi_worker.dir/libevent_multi_worker.cpp.s
.PHONY : libevent_multi_worker.cpp.s

libevent_server_ref.o: libevent_server_ref.cpp.o

.PHONY : libevent_server_ref.o

# target to build an object file
libevent_server_ref.cpp.o:
	$(MAKE) -f CMakeFiles/libevent_server_ref.dir/build.make CMakeFiles/libevent_server_ref.dir/libevent_server_ref.cpp.o
.PHONY : libevent_server_ref.cpp.o

libevent_server_ref.i: libevent_server_ref.cpp.i

.PHONY : libevent_server_ref.i

# target to preprocess a source file
libevent_server_ref.cpp.i:
	$(MAKE) -f CMakeFiles/libevent_server_ref.dir/build.make CMakeFiles/libevent_server_ref.dir/libevent_server_ref.cpp.i
.PHONY : libevent_server_ref.cpp.i

libevent_server_ref.s: libevent_server_ref.cpp.s

.PHONY : libevent_server_ref.s

# target to generate assembly for a file
libevent_server_ref.cpp.s:
	$(MAKE) -f CMakeFiles/libevent_server_ref.dir/build.make CMakeFiles/libevent_server_ref.dir/libevent_server_ref.cpp.s
.PHONY : libevent_server_ref.cpp.s

multi_queue_epoll_server.o: multi_queue_epoll_server.cpp.o

.PHONY : multi_queue_epoll_server.o

# target to build an object file
multi_queue_epoll_server.cpp.o:
	$(MAKE) -f CMakeFiles/multi_queue_epoll_server.dir/build.make CMakeFiles/multi_queue_epoll_server.dir/multi_queue_epoll_server.cpp.o
.PHONY : multi_queue_epoll_server.cpp.o

multi_queue_epoll_server.i: multi_queue_epoll_server.cpp.i

.PHONY : multi_queue_epoll_server.i

# target to preprocess a source file
multi_queue_epoll_server.cpp.i:
	$(MAKE) -f CMakeFiles/multi_queue_epoll_server.dir/build.make CMakeFiles/multi_queue_epoll_server.dir/multi_queue_epoll_server.cpp.i
.PHONY : multi_queue_epoll_server.cpp.i

multi_queue_epoll_server.s: multi_queue_epoll_server.cpp.s

.PHONY : multi_queue_epoll_server.s

# target to generate assembly for a file
multi_queue_epoll_server.cpp.s:
	$(MAKE) -f CMakeFiles/multi_queue_epoll_server.dir/build.make CMakeFiles/multi_queue_epoll_server.dir/multi_queue_epoll_server.cpp.s
.PHONY : multi_queue_epoll_server.cpp.s

multi_thread_libevent_server.o: multi_thread_libevent_server.cpp.o

.PHONY : multi_thread_libevent_server.o

# target to build an object file
multi_thread_libevent_server.cpp.o:
	$(MAKE) -f CMakeFiles/multi_thread_libevent_server.dir/build.make CMakeFiles/multi_thread_libevent_server.dir/multi_thread_libevent_server.cpp.o
.PHONY : multi_thread_libevent_server.cpp.o

multi_thread_libevent_server.i: multi_thread_libevent_server.cpp.i

.PHONY : multi_thread_libevent_server.i

# target to preprocess a source file
multi_thread_libevent_server.cpp.i:
	$(MAKE) -f CMakeFiles/multi_thread_libevent_server.dir/build.make CMakeFiles/multi_thread_libevent_server.dir/multi_thread_libevent_server.cpp.i
.PHONY : multi_thread_libevent_server.cpp.i

multi_thread_libevent_server.s: multi_thread_libevent_server.cpp.s

.PHONY : multi_thread_libevent_server.s

# target to generate assembly for a file
multi_thread_libevent_server.cpp.s:
	$(MAKE) -f CMakeFiles/multi_thread_libevent_server.dir/build.make CMakeFiles/multi_thread_libevent_server.dir/multi_thread_libevent_server.cpp.s
.PHONY : multi_thread_libevent_server.cpp.s

single_client.o: single_client.cpp.o

.PHONY : single_client.o

# target to build an object file
single_client.cpp.o:
	$(MAKE) -f CMakeFiles/single_client.dir/build.make CMakeFiles/single_client.dir/single_client.cpp.o
.PHONY : single_client.cpp.o

single_client.i: single_client.cpp.i

.PHONY : single_client.i

# target to preprocess a source file
single_client.cpp.i:
	$(MAKE) -f CMakeFiles/single_client.dir/build.make CMakeFiles/single_client.dir/single_client.cpp.i
.PHONY : single_client.cpp.i

single_client.s: single_client.cpp.s

.PHONY : single_client.s

# target to generate assembly for a file
single_client.cpp.s:
	$(MAKE) -f CMakeFiles/single_client.dir/build.make CMakeFiles/single_client.dir/single_client.cpp.s
.PHONY : single_client.cpp.s

single_queue_epoll_server.o: single_queue_epoll_server.cpp.o

.PHONY : single_queue_epoll_server.o

# target to build an object file
single_queue_epoll_server.cpp.o:
	$(MAKE) -f CMakeFiles/single_queue_epoll_server.dir/build.make CMakeFiles/single_queue_epoll_server.dir/single_queue_epoll_server.cpp.o
.PHONY : single_queue_epoll_server.cpp.o

single_queue_epoll_server.i: single_queue_epoll_server.cpp.i

.PHONY : single_queue_epoll_server.i

# target to preprocess a source file
single_queue_epoll_server.cpp.i:
	$(MAKE) -f CMakeFiles/single_queue_epoll_server.dir/build.make CMakeFiles/single_queue_epoll_server.dir/single_queue_epoll_server.cpp.i
.PHONY : single_queue_epoll_server.cpp.i

single_queue_epoll_server.s: single_queue_epoll_server.cpp.s

.PHONY : single_queue_epoll_server.s

# target to generate assembly for a file
single_queue_epoll_server.cpp.s:
	$(MAKE) -f CMakeFiles/single_queue_epoll_server.dir/build.make CMakeFiles/single_queue_epoll_server.dir/single_queue_epoll_server.cpp.s
.PHONY : single_queue_epoll_server.cpp.s

single_thread_libevent_server.o: single_thread_libevent_server.cpp.o

.PHONY : single_thread_libevent_server.o

# target to build an object file
single_thread_libevent_server.cpp.o:
	$(MAKE) -f CMakeFiles/single_thread_libevent_server.dir/build.make CMakeFiles/single_thread_libevent_server.dir/single_thread_libevent_server.cpp.o
.PHONY : single_thread_libevent_server.cpp.o

single_thread_libevent_server.i: single_thread_libevent_server.cpp.i

.PHONY : single_thread_libevent_server.i

# target to preprocess a source file
single_thread_libevent_server.cpp.i:
	$(MAKE) -f CMakeFiles/single_thread_libevent_server.dir/build.make CMakeFiles/single_thread_libevent_server.dir/single_thread_libevent_server.cpp.i
.PHONY : single_thread_libevent_server.cpp.i

single_thread_libevent_server.s: single_thread_libevent_server.cpp.s

.PHONY : single_thread_libevent_server.s

# target to generate assembly for a file
single_thread_libevent_server.cpp.s:
	$(MAKE) -f CMakeFiles/single_thread_libevent_server.dir/build.make CMakeFiles/single_thread_libevent_server.dir/single_thread_libevent_server.cpp.s
.PHONY : single_thread_libevent_server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... epoll_server_example"
	@echo "... single_client"
	@echo "... single_queue_epoll_server"
	@echo "... edit_cache"
	@echo "... single_thread_libevent_server"
	@echo "... multi_thread_libevent_server"
	@echo "... basic_server"
	@echo "... libevent_server_ref"
	@echo "... client_pool"
	@echo "... multi_queue_epoll_server"
	@echo "... libevent_multi_worker"
	@echo "... basic_server.o"
	@echo "... basic_server.i"
	@echo "... basic_server.s"
	@echo "... client_pool.o"
	@echo "... client_pool.i"
	@echo "... client_pool.s"
	@echo "... epoll_server_example.o"
	@echo "... epoll_server_example.i"
	@echo "... epoll_server_example.s"
	@echo "... libevent_multi_worker.o"
	@echo "... libevent_multi_worker.i"
	@echo "... libevent_multi_worker.s"
	@echo "... libevent_server_ref.o"
	@echo "... libevent_server_ref.i"
	@echo "... libevent_server_ref.s"
	@echo "... multi_queue_epoll_server.o"
	@echo "... multi_queue_epoll_server.i"
	@echo "... multi_queue_epoll_server.s"
	@echo "... multi_thread_libevent_server.o"
	@echo "... multi_thread_libevent_server.i"
	@echo "... multi_thread_libevent_server.s"
	@echo "... single_client.o"
	@echo "... single_client.i"
	@echo "... single_client.s"
	@echo "... single_queue_epoll_server.o"
	@echo "... single_queue_epoll_server.i"
	@echo "... single_queue_epoll_server.s"
	@echo "... single_thread_libevent_server.o"
	@echo "... single_thread_libevent_server.i"
	@echo "... single_thread_libevent_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

